name: Extract RELAX NG Schema of Atom Syndication Format

on:
  push:
    branches:
      - main
      - test-ci

jobs:
  extract:
    runs-on: ubuntu-latest
    container:
      image: ruby:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: download RFC document
      run: ruby main.rb -d

    - name: Extract schema
      run: ruby main.rb -e

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: atom.rnc
